# Generated by Django 5.1 on 2024-08-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('homepage', models.URLField(blank=True, verbose_name='Organization Homepage')),
                ('active', models.BooleanField(default=True, verbose_name='Is Organization Active?')),
                ('icon', models.ImageField(upload_to='', verbose_name='Favicon/Icon')),
                ('banner', models.ImageField(upload_to='', verbose_name='Banner Image')),
                ('twitch', models.CharField(blank=True, max_length=25, verbose_name='Twitch Channel')),
                ('twitter', models.CharField(blank=True, max_length=15, verbose_name='Twitter Username')),
                ('youtube', models.CharField(blank=True, max_length=200, verbose_name='Youtube Channel')),
            ],
            options={
                'db_table_comment': 'Organizations',
            },
        ),
    ]
