# Generated by Django 5.1 on 2024-08-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marathon",
            name="banner",
            field=models.ImageField(upload_to="", verbose_name="Banner Image"),
        ),
        migrations.AlterField(
            model_name="marathon",
            name="icon",
            field=models.ImageField(upload_to="", verbose_name="Favicon/Icon"),
        ),
    ]
