# Generated by Django 5.1.1 on 2024-09-08 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='organization',
            table_comment=None,
        ),
    ]
