# Generated by Django 5.1.1 on 2024-09-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='tracker',
            field=models.URLField(blank=True, verbose_name='Donation Tracker'),
        ),
    ]
