# Generated by Django 5.1.1 on 2024-09-14 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_organization_tracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='active',
        ),
    ]
