# Generated by Django 5.1.1 on 2024-09-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_remove_organization_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='facebook',
        ),
    ]
