# Generated by Django 5.1.1 on 2024-09-20 20:09

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(upload_to='', verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(upload_to='org-icons/', verbose_name='Favicon/Icon'),
        ),
    ]
