# Generated by Django 5.1.1 on 2024-09-20 20:10

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_organization_banner_alter_organization_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(upload_to='org-banners/', verbose_name='Banner Image'),
        ),
    ]
