# Generated by Django 5.1.1 on 2024-09-20 20:29

import imagekit.models.fields
import vgarchive.organizations.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_organization_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(upload_to=vgarchive.organizations.models._upload_banner, verbose_name='Banner Image'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(upload_to=vgarchive.organizations.models._upload_icon, verbose_name='Favicon/Icon'),
        ),
    ]
