# Generated by Django 5.1 on 2024-08-16 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
        ('events', '0001_initial'),
        ('marathons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='charity_id',
        ),
        migrations.RemoveField(
            model_name='event',
            name='marathon_id',
        ),
        migrations.AddField(
            model_name='event',
            name='charity',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='charities.charity', verbose_name='Supported Charity'),
        ),
        migrations.AddField(
            model_name='event',
            name='marathon',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='marathons.marathon', verbose_name='Marathon'),
        ),
        migrations.AlterField(
            model_name='event',
            name='donations',
            field=models.URLField(blank=True, verbose_name='Donations Page'),
        ),
        migrations.AlterField(
            model_name='event',
            name='homepage',
            field=models.URLField(blank=True, verbose_name='Event Homepage'),
        ),
        migrations.AlterField(
            model_name='event',
            name='youtube_playlist',
            field=models.URLField(blank=True, verbose_name='Youtube VOD Playlist'),
        ),
    ]
