# Generated by Django 5.1 on 2024-08-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Short Name(optional)'),
        ),
    ]
