# Generated by Django 5.1 on 2024-08-20 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_charity_id_remove_event_marathon_id_and_more'),
        ('organizations', '0005_organization_delete_marathon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='marathon',
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization', verbose_name='Organization'),
        ),
    ]
