# Generated by Django 5.1.1 on 2024-09-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_donations',
            field=models.IntegerField(default=0, verbose_name='Number of Donations'),
            preserve_default=False,
        ),
    ]
