# Generated by Django 5.1.1 on 2024-09-09 02:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_num_donations'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 22, 23, 4, 503733), verbose_name='End Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 22, 23, 12, 50610), verbose_name='Start Date and Time'),
            preserve_default=False,
        ),
    ]
