# Generated by Django 5.1.1 on 2024-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_end_datetime_event_start_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
