# Generated by Django 5.1.1 on 2024-09-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_datetime',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_datetime',
            field=models.DateField(verbose_name='Start Date'),
        ),
    ]
