# Generated by Django 5.1.1 on 2024-09-20 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_end_datetime_alter_event_start_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_datetime',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_datetime',
            new_name='start_date',
        ),
    ]
