# Generated by Django 5.1.1 on 2024-09-20 20:09

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='event-banners/', verbose_name='Banner Image'),
        ),
    ]
