# Generated by Django 5.1.3 on 2024-12-06 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgarchive', '0002_alter_event_charity_alter_event_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(choices=[('tracker', 'GDQ Tracker'), ('oengus', 'Oengus'), ('horaro', 'Horaro'), ('manual', 'Manual Import')], default='manual', max_length=10, verbose_name='Event Source'),
        ),
    ]
