# Generated by Django 5.1.3 on 2024-12-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vgarchive', '0003_alter_event_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='source',
            field=models.CharField(choices=[('tracker', 'GDQ Tracker'), ('oengus', 'Oengus'), ('horaro', 'Horaro'), ('manual', 'Manual Import')], default='manual', max_length=10, verbose_name='Run Source'),
        ),
    ]
