# Generated by Django 5.1 on 2024-08-17 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marathons', '0002_alter_marathon_banner_alter_marathon_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marathon',
            name='short_id',
        ),
    ]
