# Generated by Django 5.1 on 2024-08-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marathons', '0003_remove_marathon_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, verbose_name='Youtube Channel'),
        ),
    ]
