# Generated by Django 5.1 on 2024-08-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Display Name')),
                ('homepage', models.URLField()),
            ],
        ),
    ]
