# Generated by Django 5.1.1 on 2024-09-14 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_charity_short_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='charity',
            options={'verbose_name_plural': 'Charities'},
        ),
    ]
