# Generated by Django 5.1.1 on 2024-09-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0004_charity_bluesky_charity_facebook_charity_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charity',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='charity',
            name='linkedin',
        ),
    ]
