# Generated by Django 5.1.1 on 2024-09-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_remove_charity_facebook_remove_charity_linkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='id',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
