# Generated by Django 5.1.1 on 2024-09-20 20:09

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0006_alter_charity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='icon',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to='', verbose_name='Icon/Favicon'),
        ),
    ]
