# Generated by Django 5.1.1 on 2024-10-02 16:47

import vgarchive.validators.bluesky
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0009_alter_charity_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charity',
            name='bluesky',
            field=models.CharField(blank=True, max_length=200, validators=[vgarchive.validators.bluesky.validate_bluesky], verbose_name='Bluesky Account'),
        ),
    ]
