"""
Django settings for vgarchive project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import locale

BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.admindocs",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    # All our custom apps
    "vgarchive",
    "vgarchive.charities",
    "vgarchive.events",
    "vgarchive.organizations",
    "vgarchive.runs",
    # Tailwind CSS
    "tailwind",
    "vgarchive.theme",
    # Icons
    "django_icons",
    # Reusable components
    "slippers",
    # Better tables
    "django_tables2",
    # Compression
    "compressor",
    # HTML Minifying
    "django_minify_html",
    # Bakery
    "bakery",
]

TAILWIND_APP_NAME = "vgarchive.theme"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Compression
    "compression_middleware.middleware.CompressionMiddleware",
    # Minify HTML
    "django_minify_html.middleware.MinifyHtmlMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # admindocs
    "django.contrib.admindocs.middleware.XViewMiddleware",
]

ROOT_URLCONF = "vgarchive.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "vgarchive/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            # Autoload some additional template tags
            "builtins": [
                "slippers.templatetags.slippers",
            ],
        },
    },
]

ASGI_APPLICATION = "vgarchive.asgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/New_York"

USE_I18N = True
USE_THOUSAND_SEPARATOR = True

USE_TZ = True

# Set locale. Not part of settings, but important nonetheless
locale.setlocale(locale.LC_ALL, "")

# https://django-icons.readthedocs.io
DJANGO_ICONS = {
    "DEFAULTS": {"renderer": "django_icons_bootstrap_icons.BootstrapIconRenderer"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

COMPRESS_ENABLED = True

# Bakery

BUILD_DIR = f"{BASE_DIR}/built"

BAKERY_VIEWS = [
    "vgarchive.events.views.EventListView",
    "vgarchive.events.views.EventDetailView",
]
