# Generated by Django 5.1 on 2024-08-16 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_remove_event_charity_id_remove_event_marathon_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=200, verbose_name='Game Name')),
                ('platform', models.CharField(max_length=200, verbose_name='Platform')),
                ('length', models.DurationField(verbose_name='Run Length')),
                ('runners', models.CharField(max_length=200, verbose_name='Runners')),
                ('youtube', models.URLField()),
                ('twitch', models.URLField()),
                ('event', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
            ],
            options={
                'db_table_comment': 'Runs',
            },
        ),
    ]
