# Generated by Django 5.1.1 on 2024-09-14 19:41

import django.db.models.deletion
import vgarchive.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_run_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Game Name')),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('pronouns', models.CharField(blank=True, max_length=50, verbose_name='Pronouns')),
                ('twitch', models.CharField(blank=True, max_length=25, verbose_name='Twitch Channel')),
                ('youtube', models.CharField(blank=True, max_length=200, verbose_name='Youtube Channel')),
                ('twitter', models.CharField(blank=True, max_length=15, verbose_name='Twitter Username')),
                ('bluesky', models.CharField(blank=True, max_length=200, verbose_name='Bluesky Username')),
            ],
        ),
        migrations.RemoveField(
            model_name='run',
            name='runners',
        ),
        migrations.AlterField(
            model_name='run',
            name='twitch',
            field=models.URLField(validators=[vgarchive.utils.is_twitch_url], verbose_name='Twitch VOD Link'),
        ),
        migrations.AlterField(
            model_name='run',
            name='youtube',
            field=models.URLField(validators=[vgarchive.utils.is_youtube_url], verbose_name='Youtube VOD Link'),
        ),
        migrations.AlterField(
            model_name='run',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='runs.game', verbose_name='Game'),
        ),
        migrations.AddField(
            model_name='run',
            name='runners',
            field=models.ManyToManyField(to='runs.runner', verbose_name='Runners'),
        ),
    ]
