# Generated by Django 5.1.1 on 2024-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_alter_run_twitch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
