# Generated by Django 5.1.1 on 2024-09-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_alter_game_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='id',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
