# Generated by Django 5.1.1 on 2024-09-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_alter_run_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='id',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
